format = """
[  ](bg:#85fa89 fg:#222222)\
[](fg:#85fa89)\
$directory\
$git_branch\
$git_status\
$nodejs\
$rust\
$golang\
$php\
$time\
\n$character"""

[character]
success_symbol = '[\[⊤\]](bold #85fa89)'
error_symbol = '[\[⊥\]](bold #c07070)'

[directory]
style = "fg:#85fa89 "
format = "[ $path]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"~/Documents" = " "
"~/Downloads" = "󰇚 "
"~/Music/long" = "󰽮 "
"~/Music/energetic" = "󰽰 "
"~/Music/slow" = "󰽯 "
"~/Music" = "󰝚 "
"~/Pictures" = "  "
"~/Scripts" = "  "
[git_branch]
symbol = "| "
format = '[[ $symbol $branch ](fg:#85fa89)]($style)'

[git_status]
format = '[[($all_status$ahead_behind )](fg:#85fa89)]($style)'

[nodejs]
symbol = "| "
format = '[[ $symbol ($version) ](fg:#85fa89)]($style)'

[rust]
symbol = "| "
format = '[[ $symbol ($version) ](fg:#85fa89)]($style)'

[golang]
symbol = "| ﳑ"
format = '[[ $symbol ($version) ](fg:#85fa89)]($style)'

[php]
symbol = "| "
format = '[[ $symbol ($version) ](fg:#85fa89)]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
format = '[[  $time ](fg:#85fa89)]($style)'

